apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    image.openshift.io/triggers: |-
      [
        {
          "from": {
            "kind": "ImageStreamTag",
            "name": "{{ .Values.imageStream.name }}:{{.Values.imageStream.tag }}"
          },
          "fieldPath": "spec.template.spec.containers[0].image"
        }
      ]
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.imageStream.name }}:{{.Values.imageStream.tag }}"
          resources:
              requests:
                cpu: 100m
                memory: "100Mi"
              limits:
                cpu: 200m
                memory: "150Mi" 
          ports:
            - containerPort: 8080
              protocol: TCP                
          env:
            - name: ASPNETCORE_URLS
              value: "http://*:8080"
          volumeMounts:
            - mountPath: /app/appsettings.json
              name: appsettings-volume
              subPath: appsettings.json
      imagePullSecrets:
        - name: artifactory-pullsecret
      volumes:
      - name: appsettings-volume
        configMap:
          name: appsettings-{{ .Values.name }}
          items:
            - key: appsettings.json
              path: appsettings.json

