kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}  
spec:
  host: {{ .Values.name }}-{{ .Values.namespace }}.apps-crc.testing
  to:
    kind: Service
    name: {{ .Values.name }}
    weight: 100
  port:
    targetPort: proxy
  tls:
    termination: reencrypt
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
