apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: toolkit-tls  
  labels:
    app: {{ .Values.name }}
    service: {{ .Values.name }}    
spec:
  type: ClusterIP
  ports:
    # - name: https
    #   port: 8080
    #   protocol: TCP
    #   targetPort: 7143
    - name: https
      port: 8888
      protocol: TCP
      targetPort: 8888 
  selector:
    app: {{ .Values.name }}