kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.name }}-proxy
  namespace: {{ .Values.namespace }}
data:
  session_secret: SkluenNDQVUwamlBSUlpcVNaZEhkd0UxTzRwc2FXVnBKTjBpNGJGblpDTQ==
type: Opaque
