kind: DestinationRule
apiVersion: networking.istio.io/v1beta1
metadata:
  name: default-destination-rule
  namespace: robotorium-servicemesh
spec:
  host: '*.local'
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
