apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata: 
  name: allow-ingress
  namespace: {{ .Values.namespace }}  
spec: 
  action: ALLOW
  rules:
   - to:
      - operation:
         paths:
           - /*
  selector:
     matchLabels: 
       app: istio-ingressgateway
    